<a href="https://colab.research.google.com/github/ibrahimmhammed/projects/blob/main/heart_failure_predection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Importing**


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
data = pd.read_csv("//content//heart.csv")

***Exploring*** **and** **describing**


In [ ]:
#to explore data
data.head(10)
data.shape
data.info()


In [ ]:
#to describe data
data.describe()

Age   RestingBP  Cholesterol   FastingBS       MaxHR  \
count  918.000000  918.000000   918.000000  918.000000  918.000000   
mean    53.510893  132.396514   198.799564    0.233115  136.809368   
std      9.432617   18.514154   109.384145    0.423046   25.460334   
min     28.000000    0.000000     0.000000    0.000000   60.000000   
25%     47.000000  120.000000   173.250000    0.000000  120.000000   
50%     54.000000  130.000000   223.000000    0.000000  138.000000   
75%     60.000000  140.000000   267.000000    0.000000  156.000000   
max     77.000000  200.000000   603.000000    1.000000  202.000000   

          Oldpeak  HeartDisease  
count  918.000000    918.000000  
mean     0.887364      0.553377  
std      1.066570      0.497414  
min     -2.600000      0.000000  
25%      0.000000      0.000000  
50%      0.600000      1.000000  
75%      1.500000      1.000000  
max      6.200000      1.000000

In [ ]:
#data cleaning
data.isnull().sum()
data.duplicated().sum()

0

# **Analysis**


In [ ]:
#counting patients
data["HeartDisease"].value_counts()

In [ ]:
#visulazation
data.hist(figsize=(20,20))
plt.show()

In [ ]:
#measuring correlation
cor =data.corr()
sns.heatmap(cor, annot=True,fmt=".2f", linewidths=0.5)

# **processing** **data**


In [ ]:
#to convert data from object to numerical
from sklearn.preprocessing import LabelEncoder
lab = LabelEncoder()
obj = data.select_dtypes(include = "object")
non_obj = data.select_dtypes(exclude = "object")
for i in range(0,obj.shape[1]):
  obj.iloc[:,i]=lab.fit_transform(obj.iloc[:,i])


In [ ]:
#to concatenate obj and non_obj in a datafreme
df = pd.concat([obj,non_obj],axis=1)
df

# **Model**

In [ ]:
#importing modules

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report




In [ ]:
#difining x and y
x = df.drop(["HeartDisease"],axis=1)
y= df["HeartDisease"]

In [ ]:
#spliting train and test
x_train,x_test,y_train,y_test= train_test_split(x,y,train_size=0.7,shuffle="true",random_state=44)


In [ ]:
#testing the model
def testing(model):
  model.fit(x_train,y_train)
  predictid_data = model.predict(x_test)
  print("confusion matrix is \n ", confusion_matrix(predictid_data,y_test))
  print("classification report is \n ", classification_report(predictid_data,y_test))





# **Applying** **algorithms**

In [ ]:
# 1- k_neighpors
k_neighpors = KNeighborsClassifier()
testing(k_neighpors)

confusion matrix is 
  [[ 93  40]
 [ 33 110]]
classification report is 
                precision    recall  f1-score   support

           0       0.74      0.70      0.72       133
           1       0.73      0.77      0.75       143

    accuracy                           0.74       276
   macro avg       0.74      0.73      0.73       276
weighted avg       0.74      0.74      0.74       276



In [ ]:
# 2- decision_tree
decision_tree = DecisionTreeClassifier()
testing(decision_tree)

confusion matrix is 
  [[ 98  25]
 [ 28 125]]
classification report is 
                precision    recall  f1-score   support

           0       0.78      0.80      0.79       123
           1       0.83      0.82      0.83       153

    accuracy                           0.81       276
   macro avg       0.81      0.81      0.81       276
weighted avg       0.81      0.81      0.81       276



In [ ]:
# 3- GaussianNB
gaussian_nb = GaussianNB()
testing(gaussian_nb)


confusion matrix is 
  [[105  20]
 [ 21 130]]
classification report is 
                precision    recall  f1-score   support

           0       0.83      0.84      0.84       125
           1       0.87      0.86      0.86       151

    accuracy                           0.85       276
   macro avg       0.85      0.85      0.85       276
weighted avg       0.85      0.85      0.85       276



In [ ]:
#4- SVC
svc = SVC()
testing(svc)

In [ ]:
#5- RandomForestClassifier
random_forest = RandomForestClassifier(n_estimators=500,criterion="gini")
testing(random_forest)

confusion matrix is 
  [[110  12]
 [ 16 138]]
classification report is 
                precision    recall  f1-score   support

           0       0.87      0.90      0.89       122
           1       0.92      0.90      0.91       154

    accuracy                           0.90       276
   macro avg       0.90      0.90      0.90       276
weighted avg       0.90      0.90      0.90       276



In [ ]:
#6- GradientBoostingClassifier
gradient_boosting = GradientBoostingClassifier(learning_rate=0.01,n_estimators=500,loss="exponential",criterion="squared_error")
testing(gradient_boosting)

confusion matrix is 
  [[107  18]
 [ 19 132]]
classification report is 
                precision    recall  f1-score   support

           0       0.85      0.86      0.85       125
           1       0.88      0.87      0.88       151

    accuracy                           0.87       276
   macro avg       0.86      0.87      0.86       276
weighted avg       0.87      0.87      0.87       276

